# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\maeve\Desktop\nb_app\ui\postpop.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_postpop(object):
    def setupUi(self, postpop):
        postpop.setObjectName("postpop")
        postpop.resize(521, 534)
        self.centralwidget = QtWidgets.QWidget(postpop)
        self.centralwidget.setGeometry(QtCore.QRect(0, 0, 651, 561))
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-20, 0, 691, 561))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.widget.setObjectName("widget")
        self.dl1 = QtWidgets.QLineEdit(self.widget)
        self.dl1.setGeometry(QtCore.QRect(100, 320, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Swis721 BT")
        font.setPointSize(12)
        self.dl1.setFont(font)
        self.dl1.setStyleSheet("background-color: none; border-radius: 10px; color: grey;   border: 1px solid black;\n"
"")
        self.dl1.setText("")
        self.dl1.setAlignment(QtCore.Qt.AlignCenter)
        self.dl1.setObjectName("dl1")
        self.ps1 = QtWidgets.QLineEdit(self.widget)
        self.ps1.setGeometry(QtCore.QRect(100, 160, 361, 81))
        font = QtGui.QFont()
        font.setFamily("Swis721 BT")
        font.setPointSize(12)
        font.setStrikeOut(False)
        self.ps1.setFont(font)
        self.ps1.setStyleSheet("background-color: none; border-radius: 10px; color: grey;   border: 1px solid black;\n"
"")
        self.ps1.setText("")
        self.ps1.setAlignment(QtCore.Qt.AlignCenter)
        self.ps1.setObjectName("ps1")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(100, 276, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Swis721 BT")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: transparent; border: none; color: grey;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(100, 120, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Swis721 BT")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: transparent; border: none; color: grey;")
        self.label_2.setObjectName("label_2")
        self.addpost_btn = QtWidgets.QPushButton(self.widget)
        self.addpost_btn.setGeometry(QtCore.QRect(100, 400, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display")
        font.setPointSize(15)
        self.addpost_btn.setFont(font)
        self.addpost_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addpost_btn.setStyleSheet("QPushButton {background-color: rgb(21, 21, 21); border-radius: 30px; color: white;}\n"
"\n"
"QPushButton:hover {border-radius: 30px; color: white; background-color: rgb(85, 170, 255);}\n"
"")
        self.addpost_btn.setObjectName("addpost_btn")
        self.frm_board = QtWidgets.QListWidget(self.widget)
        self.frm_board.setGeometry(QtCore.QRect(40, 20, 481, 491))
        self.frm_board.setStyleSheet(" border-radius: 20px; border: 1px solid grey; \n"
"background-color: rgb(255, 255, 255);")
        self.frm_board.setObjectName("frm_board")
        self.tags_pinfo = QtWidgets.QPushButton(self.widget)
        self.tags_pinfo.setEnabled(False)
        self.tags_pinfo.setGeometry(QtCore.QRect(69, 41, 130, 37))
        font = QtGui.QFont()
        font.setFamily("Swis721 BT")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tags_pinfo.setFont(font)
        self.tags_pinfo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tags_pinfo.setStyleSheet("background-color: none; border-radius: 18px; color: black;   border: 1px solid grey;")
        self.tags_pinfo.setObjectName("tags_pinfo")
        self.postback_btn = QtWidgets.QPushButton(self.widget)
        self.postback_btn.setEnabled(True)
        self.postback_btn.setGeometry(QtCore.QRect(210, 40, 71, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.postback_btn.setFont(font)
        self.postback_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.postback_btn.setStyleSheet("QPushButton {border-radius: 20px; color: white; background-color: rgb(255, 85, 127);}\n"
"\n"
"QPushButton:hover {border-radius: 20px; border: 1px solid #FF557F; color: rgb(255, 85, 127); background-color: white; }\n"
"")
        self.postback_btn.setObjectName("postback_btn")
        self.frm_board_2 = QtWidgets.QListWidget(self.widget)
        self.frm_board_2.setGeometry(QtCore.QRect(70, 100, 421, 381))
        self.frm_board_2.setStyleSheet(" border-radius: 20px;\n"
"background-color: rgb(243, 243, 243);")
        self.frm_board_2.setObjectName("frm_board_2")
        self.frm_board.raise_()
        self.frm_board_2.raise_()
        self.addpost_btn.raise_()
        self.dl1.raise_()
        self.ps1.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.tags_pinfo.raise_()
        self.postback_btn.raise_()

        self.retranslateUi(postpop)
        QtCore.QMetaObject.connectSlotsByName(postpop)

    def retranslateUi(self, postpop):
        _translate = QtCore.QCoreApplication.translate
        postpop.setWindowTitle(_translate("postpop", "MainWindow"))
        self.dl1.setPlaceholderText(_translate("postpop", "Until when?"))
        self.ps1.setPlaceholderText(_translate("postpop", "What to post?"))
        self.label.setText(_translate("postpop", "Deadline: "))
        self.label_2.setText(_translate("postpop", "Post: "))
        self.addpost_btn.setText(_translate("postpop", "Confirm"))
        self.tags_pinfo.setText(_translate("postpop", "Add Post"))
        self.postback_btn.setText(_translate("postpop", "Back"))
