# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\maeve\Desktop\nb_app\ui\signup.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signup(object):
    def setupUi(self, signup):
        signup.setObjectName("signup")
        signup.resize(1042, 574)
        self.centralwidget = QtWidgets.QWidget(signup)
        self.centralwidget.setGeometry(QtCore.QRect(0, 0, 1081, 591))
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1081, 591))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QtCore.QRect(70, 200, 421, 311))
        self.pushButton.setStyleSheet("background-color: rgb(255, 204, 204); border-radius: 15px;\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(70, 144, 911, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(70, 50, 131, 36))
        font = QtGui.QFont()
        font.setFamily("Swis721 BT")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 246, 214); border-radius: 10px; color: rgb(252, 201, 93);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setEnabled(False)
        self.label_16.setGeometry(QtCore.QRect(456, 101, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setToolTip("")
        self.label_16.setAutoFillBackground(False)
        self.label_16.setStyleSheet("background-color: NONE; \n"
"color: rgb(0, 0, 0);")
        self.label_16.setObjectName("label_16")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setEnabled(False)
        self.widget_2.setGeometry(QtCore.QRect(100, 270, 361, 211))
        self.widget_2.setStyleSheet("background-color: rgb(249, 249, 249);\n"
"border-radius: 15px;\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(250, 230, 211, 188))
        self.widget_3.setStyleSheet("background-color: rgb(249, 249, 249);\n"
"border-radius: 15px;\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.logteach_btn = QtWidgets.QPushButton(self.widget_3)
        self.logteach_btn.setEnabled(True)
        self.logteach_btn.setGeometry(QtCore.QRect(20, 20, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Swis721 BT")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.logteach_btn.setFont(font)
        self.logteach_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logteach_btn.setStyleSheet("background-color:  rgb(255, 157, 157); border-radius: 10px; color: white;\n"
"color: rgb(255, 204, 204);")
        self.logteach_btn.setObjectName("logteach_btn")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(122, 228, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: none;\n"
"color: rgb(255, 157, 157);")
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(130, 334, 301, 121))
        self.textEdit.setStyleSheet("background-color: transparent; border: none;")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_2.setEnabled(False)
        self.textEdit_2.setGeometry(QtCore.QRect(624, 351, 301, 121))
        self.textEdit_2.setStyleSheet("background-color: transparent; border: none;")
        self.textEdit_2.setObjectName("textEdit_2")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setEnabled(False)
        self.widget_4.setGeometry(QtCore.QRect(593, 272, 361, 211))
        self.widget_4.setStyleSheet("background-color: rgb(249, 249, 249);\n"
"border-radius: 15px;\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QtCore.QRect(561, 200, 421, 311))
        self.pushButton_2.setStyleSheet("background-color:  rgb(222, 235, 247); border-radius: 15px;\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(613, 230, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: none;\n"
"color: rgb(162, 198, 232);")
        self.label_2.setObjectName("label_2")
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setGeometry(QtCore.QRect(744, 232, 211, 188))
        self.widget_5.setStyleSheet("background-color: rgb(249, 249, 249);\n"
"border-radius: 15px;\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.logstud_btn = QtWidgets.QPushButton(self.widget_5)
        self.logstud_btn.setEnabled(True)
        self.logstud_btn.setGeometry(QtCore.QRect(20, 20, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Swis721 BT")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.logstud_btn.setFont(font)
        self.logstud_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logstud_btn.setStyleSheet("background-color:  rgb(162, 198, 232); border-radius: 10px; color: white;\n"
"color:  rgb(222, 235, 247);")
        self.logstud_btn.setObjectName("logstud_btn")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(850, 50, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Swis721 BT")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("background-color: rgb(21, 21, 21); border-radius: 10px; color: white;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setGeometry(QtCore.QRect(20, 20, 1001, 531))
        self.widget_6.setStyleSheet("border: 1px solid grey;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px; ")
        self.widget_6.setObjectName("widget_6")
        self.widget_6.raise_()
        self.pushButton_2.raise_()
        self.pushButton.raise_()
        self.line.raise_()
        self.pushButton_5.raise_()
        self.label_16.raise_()
        self.widget_2.raise_()
        self.widget_3.raise_()
        self.label.raise_()
        self.textEdit.raise_()
        self.widget_4.raise_()
        self.label_2.raise_()
        self.widget_5.raise_()
        self.textEdit_2.raise_()
        self.pushButton_4.raise_()

        self.retranslateUi(signup)
        QtCore.QMetaObject.connectSlotsByName(signup)

    def retranslateUi(self, signup):
        _translate = QtCore.QCoreApplication.translate
        signup.setWindowTitle(_translate("signup", "MainWindow"))
        self.pushButton_5.setText(_translate("signup", "Sign Up"))
        self.label_16.setText(_translate("signup", "Who are you?"))
        self.logteach_btn.setText(_translate("signup", "Continue"))
        self.label.setText(_translate("signup", "Teacher"))
        self.textEdit.setHtml(_translate("signup", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:16pt; color:#ff9e9e;\">Empower your passion for teaching, sign up and inspire minds today! </span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("signup", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:16pt; color:#a2c6e8;\">Sign up now and ignite your curiosity! </span></p></body></html>"))
        self.label_2.setText(_translate("signup", "Student"))
        self.logstud_btn.setText(_translate("signup", "Continue"))
        self.pushButton_4.setText(_translate("signup", "Back"))
