# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'creo-0.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_creo_landingpage(object):
    def setupUi(self, creo_landingpage):
        creo_landingpage.setObjectName("creo_landingpage")
        creo_landingpage.resize(790, 875)
        creo_landingpage.setMinimumSize(QtCore.QSize(779, 848))
        creo_landingpage.setStyleSheet("background-color: rgb(255, 87, 51);")
        self.centralwidget = QtWidgets.QWidget(creo_landingpage)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 161))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 138, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 431))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(152, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setMinimumSize(QtCore.QSize(401, 411))
        self.label.setMaximumSize(QtCore.QSize(411, 411))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/creo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 0, 1, 2, 1)
        spacerItem2 = QtWidgets.QSpacerItem(151, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frame_5, 1, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(20, 116, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_4, 2, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(761, 60))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 0, 1, 1)
        self.name_bar = QtWidgets.QLineEdit(self.frame_2)
        self.name_bar.setMinimumSize(QtCore.QSize(341, 0))
        self.name_bar.setMaximumSize(QtCore.QSize(16777215, 41))
        self.name_bar.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #ccc;           \n"
"    border-radius: 20px;           \n"
"    padding: 10px;                   \n"
"    font-size: 16px;           \n"
"    color: #333;      \n"
"    background-color: #fff;\n"
"    \n"
"    font: 25 8pt \"Segoe UI\";\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0078d7; \n"
"    background-color: #f0f8ff;       \n"
"}\n"
"\n"
"")
        self.name_bar.setInputMask("")
        self.name_bar.setText("")
        self.name_bar.setAlignment(QtCore.Qt.AlignCenter)
        self.name_bar.setClearButtonEnabled(False)
        self.name_bar.setObjectName("name_bar")
        self.gridLayout_4.addWidget(self.name_bar, 0, 1, 1, 1)
        self.continue_btn = QtWidgets.QPushButton(self.frame_2)
        self.continue_btn.setMinimumSize(QtCore.QSize(120, 41))
        self.continue_btn.setStyleSheet("QPushButton {\n"
"    border-radius: 20px; \n"
"    border: 1px solid rgb(255, 255, 255);\n"
"    font: 87 9pt \"Segoe UI Black\";\n"
"    color: white; \n"
"    background-color: transparent; \n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: white; \n"
"    color:  rgb(255, 87, 51);; \n"
"}\n"
"")
        self.continue_btn.setObjectName("continue_btn")
        self.gridLayout_4.addWidget(self.continue_btn, 0, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        creo_landingpage.setCentralWidget(self.centralwidget)

        self.retranslateUi(creo_landingpage)
        QtCore.QMetaObject.connectSlotsByName(creo_landingpage)

    def retranslateUi(self, creo_landingpage):
        _translate = QtCore.QCoreApplication.translate
        creo_landingpage.setWindowTitle(_translate("creo_landingpage", "MainWindow"))
        self.name_bar.setPlaceholderText(_translate("creo_landingpage", "What\'s your name:"))
        self.continue_btn.setText(_translate("creo_landingpage", "Continue"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    creo_landingpage = QtWidgets.QMainWindow()
    ui = Ui_creo_landingpage()
    ui.setupUi(creo_landingpage)
    creo_landingpage.show()
    sys.exit(app.exec_())
