# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\maeve\Desktop\nb_app\ui\login_student.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_student(object):
    def setupUi(self, login_student):
        login_student.setObjectName("login_student")
        login_student.resize(1055, 549)
        self.centralwidget = QtWidgets.QWidget(login_student)
        self.centralwidget.setGeometry(QtCore.QRect(0, 0, 1091, 601))
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-10, 0, 1111, 601))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.widget.setObjectName("widget")
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setGeometry(QtCore.QRect(70, 150, 911, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setGeometry(QtCore.QRect(60, 40, 131, 36))
        font = QtGui.QFont()
        font.setFamily("Swis721 BT")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 236, 200); border-radius: 10px; color: rgb(248, 117, 36);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setEnabled(False)
        self.label_16.setGeometry(QtCore.QRect(460, 110, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setToolTip("")
        self.label_16.setAutoFillBackground(False)
        self.label_16.setStyleSheet("background-color: NONE;")
        self.label_16.setObjectName("label_16")
        self.SUTEXT_2 = QtWidgets.QTextEdit(self.widget)
        self.SUTEXT_2.setEnabled(False)
        self.SUTEXT_2.setGeometry(QtCore.QRect(360, 197, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.SUTEXT_2.setFont(font)
        self.SUTEXT_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.SUTEXT_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.SUTEXT_2.setStyleSheet("background-color: transparent; border: none;")
        self.SUTEXT_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SUTEXT_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SUTEXT_2.setObjectName("SUTEXT_2")
        self.SUTEXT_3 = QtWidgets.QTextEdit(self.widget)
        self.SUTEXT_3.setEnabled(False)
        self.SUTEXT_3.setGeometry(QtCore.QRect(360, 324, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.SUTEXT_3.setFont(font)
        self.SUTEXT_3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.SUTEXT_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.SUTEXT_3.setStyleSheet("background-color: transparent; border: none;")
        self.SUTEXT_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SUTEXT_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SUTEXT_3.setObjectName("SUTEXT_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setEnabled(False)
        self.pushButton_8.setGeometry(QtCore.QRect(480, 48, 130, 37))
        font = QtGui.QFont()
        font.setFamily("Swis721 BT")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_8.setStyleSheet("background-color: none; border-radius: 18px; color: black;   border: 1px solid black;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.ltu1 = QtWidgets.QLineEdit(self.widget)
        self.ltu1.setGeometry(QtCore.QRect(360, 240, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Swis721 BT")
        font.setPointSize(12)
        font.setStrikeOut(False)
        self.ltu1.setFont(font)
        self.ltu1.setStyleSheet("background-color: none; border-radius: 20px; color: grey;   border: 1px solid black;")
        self.ltu1.setText("")
        self.ltu1.setAlignment(QtCore.Qt.AlignCenter)
        self.ltu1.setObjectName("ltu1")
        self.ltp1 = QtWidgets.QLineEdit(self.widget)
        self.ltp1.setGeometry(QtCore.QRect(360, 370, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Swis721 BT")
        font.setPointSize(12)
        self.ltp1.setFont(font)
        self.ltp1.setStyleSheet("background-color: none; border-radius: 20px; color: grey;   border: 1px solid black;")
        self.ltp1.setText("")
        self.ltp1.setAlignment(QtCore.Qt.AlignCenter)
        self.ltp1.setObjectName("ltp1")
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_10.setGeometry(QtCore.QRect(490, 460, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Swis721 BT")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton {border-radius: 20px; color: white; background-color: rgb(85, 170, 255);}\n"
"\n"
"QPushButton:hover {border-radius: 20px; border: 1px solid #55AAFF; color: rgb(85, 170, 255); background-color: white; }")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.widget)
        self.pushButton_11.setGeometry(QtCore.QRect(880, 40, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Swis721 BT")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setStyleSheet("QPushButton {background-color: rgb(21, 21, 21); border-radius: 20px; color: white;}\n"
"\n"
"QPushButton:hover {border-radius: 20px; color: white; background-color: rgb(255, 85, 127);}\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")

        self.retranslateUi(login_student)
        QtCore.QMetaObject.connectSlotsByName(login_student)

    def retranslateUi(self, login_student):
        _translate = QtCore.QCoreApplication.translate
        login_student.setWindowTitle(_translate("login_student", "MainWindow"))
        self.pushButton_5.setText(_translate("login_student", "Log In"))
        self.label_16.setText(_translate("login_student", "Enter Credentials!"))
        self.SUTEXT_2.setHtml(_translate("login_student", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#a9a8a7;\">Username: </span></p></body></html>"))
        self.SUTEXT_3.setHtml(_translate("login_student", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#a9a8a7;\">Password: </span></p></body></html>"))
        self.pushButton_8.setText(_translate("login_student", "Student"))
        self.ltu1.setPlaceholderText(_translate("login_student", "Type your username:"))
        self.ltp1.setPlaceholderText(_translate("login_student", "Type your password:"))
        self.pushButton_10.setText(_translate("login_student", "Done"))
        self.pushButton_11.setText(_translate("login_student", "Back"))
