# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\maeve\Desktop\nb_app\ui\startup.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_startup(object):
    def setupUi(self, startup):
        startup.setObjectName("startup")
        startup.resize(1058, 558)
        self.centralwidget = QtWidgets.QWidget(startup)
        self.centralwidget.setGeometry(QtCore.QRect(0, 0, 1091, 561))
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-20, -30, 1131, 621))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(50, 330, 488, 231))
        self.widget.setStyleSheet("background-color: rgb(255, 236, 200); border-radius: 10px;  border: 1px;")
        self.widget.setObjectName("widget")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setGeometry(QtCore.QRect(20, 50, 451, 161))
        self.widget_4.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.widget_4.setObjectName("widget_4")
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setGeometry(QtCore.QRect(160, 21, 311, 101))
        self.widget_5.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.widget_5.setObjectName("widget_5")
        self.lib = QtWidgets.QPushButton(self.widget_5)
        self.lib.setEnabled(True)
        self.lib.setGeometry(QtCore.QRect(20, 10, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Swis721 BT")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lib.setFont(font)
        self.lib.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lib.setStyleSheet("background-color:  rgb(203, 146, 48); border-radius: 10px; color: white;\n"
"color: rgb(255, 236, 200);")
        self.lib.setObjectName("lib")
        self.label_25 = QtWidgets.QLabel(self.widget)
        self.label_25.setEnabled(True)
        self.label_25.setGeometry(QtCore.QRect(50, 14, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setToolTip("")
        self.label_25.setAutoFillBackground(False)
        self.label_25.setStyleSheet("background-color: NONE; \n"
"color: rgb(203, 146, 48);")
        self.label_25.setObjectName("label_25")
        self.widget_3 = QtWidgets.QWidget(self.frame)
        self.widget_3.setGeometry(QtCore.QRect(51, 125, 1001, 181))
        self.widget_3.setStyleSheet("border-radius: 10px;  border: 1px;\n"
"background-color: rgb(244, 244, 244);")
        self.widget_3.setObjectName("widget_3")
        self.label_5 = QtWidgets.QLabel(self.widget_3)
        self.label_5.setGeometry(QtCore.QRect(960, 0, 200, 198))
        self.label_5.setStyleSheet("background-color: none;\n"
"border-radius: 99%; /* Make it circular */\n"
"border: 2px solid ; /* Add a border */\n"
"border-color: rgb(0, 0, 0);\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setGeometry(QtCore.QRect(930, 130, 200, 198))
        self.label_6.setStyleSheet("background-color: none;\n"
"border-radius: 99%; /* Make it circular */\n"
"border: 2px solid ; /* Add a border */\n"
"border-color: rgb(0, 0, 0);\n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_3)
        self.label_7.setGeometry(QtCore.QRect(980, 50, 200, 198))
        self.label_7.setStyleSheet("background-color: none;\n"
"border-radius: 99%; /* Make it circular */\n"
"border: 2px solid ; /* Add a border */\n"
"border-color: rgb(0, 0, 0);\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setGeometry(QtCore.QRect(740, -160, 200, 198))
        self.label_8.setStyleSheet("background-color: none;\n"
"border-radius: 99%; /* Make it circular */\n"
"border: 2px solid ; /* Add a border */\n"
"border-color: rgb(0, 0, 0);\n"
"")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.widget_3)
        self.label_11.setGeometry(QtCore.QRect(-80, 160, 200, 198))
        self.label_11.setStyleSheet("background-color: none;\n"
"border-radius: 99%; /* Make it circular */\n"
"border: 2px solid ; /* Add a border */\n"
"border-color: rgb(0, 0, 0);\n"
"")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setGeometry(QtCore.QRect(611, 157, 200, 198))
        self.label_9.setStyleSheet("background-color: none;\n"
"border-radius: 99%; /* Make it circular */\n"
"border: 2px solid ; /* Add a border */\n"
"border-color: rgb(0, 0, 0);\n"
"")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_13 = QtWidgets.QLabel(self.widget_3)
        self.label_13.setGeometry(QtCore.QRect(708, 129, 200, 198))
        self.label_13.setStyleSheet("background-color: none;\n"
"border-radius: 99%; /* Make it circular */\n"
"border: 2px solid ; /* Add a border */\n"
"border-color: rgb(0, 0, 0);\n"
"")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.widget_3)
        self.label_15.setGeometry(QtCore.QRect(670, -180, 200, 198))
        self.label_15.setStyleSheet("background-color: none;\n"
"border-radius: 99%; /* Make it circular */\n"
"border: 2px solid ; /* Add a border */\n"
"border-color: rgb(0, 0, 0);\n"
"")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.SUTEXT_11 = QtWidgets.QTextEdit(self.frame)
        self.SUTEXT_11.setEnabled(False)
        self.SUTEXT_11.setGeometry(QtCore.QRect(94, 417, 411, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.SUTEXT_11.setFont(font)
        self.SUTEXT_11.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.SUTEXT_11.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.SUTEXT_11.setStyleSheet("background-color: transparent; border: none;\n"
"")
        self.SUTEXT_11.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SUTEXT_11.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SUTEXT_11.setObjectName("SUTEXT_11")
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setEnabled(True)
        self.widget_2.setGeometry(QtCore.QRect(560, 330, 488, 231))
        self.widget_2.setStyleSheet("background-color: rgb(250, 222, 201); border-radius: 10px;  border: 1px;")
        self.widget_2.setObjectName("widget_2")
        self.widget_10 = QtWidgets.QWidget(self.widget_2)
        self.widget_10.setEnabled(True)
        self.widget_10.setGeometry(QtCore.QRect(20, 50, 451, 161))
        self.widget_10.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.widget_10.setObjectName("widget_10")
        self.widget_11 = QtWidgets.QWidget(self.widget_2)
        self.widget_11.setEnabled(True)
        self.widget_11.setGeometry(QtCore.QRect(160, 21, 311, 101))
        self.widget_11.setStyleSheet("border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.widget_11.setObjectName("widget_11")
        self.sub = QtWidgets.QPushButton(self.widget_11)
        self.sub.setEnabled(True)
        self.sub.setGeometry(QtCore.QRect(20, 10, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Swis721 BT")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.sub.setFont(font)
        self.sub.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sub.setStyleSheet("background-color:  rgb(216, 130, 59); border-radius: 10px; color: white;\n"
"color: rgb(250, 222, 201);")
        self.sub.setObjectName("sub")
        self.label_28 = QtWidgets.QLabel(self.widget_2)
        self.label_28.setEnabled(False)
        self.label_28.setGeometry(QtCore.QRect(40, 14, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setToolTip("")
        self.label_28.setAutoFillBackground(False)
        self.label_28.setStyleSheet("background-color: NONE; \n"
"color: rgb(216, 130, 59);")
        self.label_28.setObjectName("label_28")
        self.SUTEXT_13 = QtWidgets.QTextEdit(self.frame)
        self.SUTEXT_13.setEnabled(False)
        self.SUTEXT_13.setGeometry(QtCore.QRect(616, 416, 381, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.SUTEXT_13.setFont(font)
        self.SUTEXT_13.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.SUTEXT_13.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.SUTEXT_13.setStyleSheet("background-color: transparent; border: none;\n"
"")
        self.SUTEXT_13.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SUTEXT_13.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SUTEXT_13.setObjectName("SUTEXT_13")
        self.widget_12 = QtWidgets.QWidget(self.frame)
        self.widget_12.setGeometry(QtCore.QRect(50, 60, 441, 211))
        self.widget_12.setStyleSheet("border-radius: 10px;  border: 1px;\n"
"background-color: rgb(244, 244, 244);")
        self.widget_12.setObjectName("widget_12")
        self.mainpagetext_42 = QtWidgets.QLabel(self.widget_12)
        self.mainpagetext_42.setGeometry(QtCore.QRect(58, 24, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Swis721 BlkEx BT")
        font.setPointSize(21)
        self.mainpagetext_42.setFont(font)
        self.mainpagetext_42.setToolTip("")
        self.mainpagetext_42.setAutoFillBackground(False)
        self.mainpagetext_42.setStyleSheet("background-color: transparent; border: none")
        self.mainpagetext_42.setObjectName("mainpagetext_42")
        self.mainpagetext_43 = QtWidgets.QLabel(self.widget_12)
        self.mainpagetext_43.setGeometry(QtCore.QRect(62, 26, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Swis721 BlkOul BT")
        font.setPointSize(26)
        self.mainpagetext_43.setFont(font)
        self.mainpagetext_43.setToolTip("")
        self.mainpagetext_43.setAutoFillBackground(False)
        self.mainpagetext_43.setStyleSheet("background-color: transparent; border: none")
        self.mainpagetext_43.setObjectName("mainpagetext_43")
        self.label_10 = QtWidgets.QLabel(self.widget_12)
        self.label_10.setGeometry(QtCore.QRect(-170, -70, 200, 198))
        self.label_10.setStyleSheet("background-color: none;\n"
"border-radius: 99%; /* Make it circular */\n"
"border: 2px solid ; /* Add a border */\n"
"border-color: rgb(0, 0, 0);\n"
"")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.widget_12)
        self.label_12.setGeometry(QtCore.QRect(-66, -179, 200, 198))
        self.label_12.setStyleSheet("background-color: none;\n"
"border-radius: 99%; /* Make it circular */\n"
"border: 2px solid ; /* Add a border */\n"
"border-color: rgb(0, 0, 0);\n"
"")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_14 = QtWidgets.QLabel(self.widget_12)
        self.label_14.setGeometry(QtCore.QRect(350, -150, 200, 198))
        self.label_14.setStyleSheet("background-color: none;\n"
"border-radius: 99%; /* Make it circular */\n"
"border: 2px solid ; /* Add a border */\n"
"border-color: rgb(0, 0, 0);\n"
"")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.abb = QtWidgets.QPushButton(self.frame)
        self.abb.setEnabled(True)
        self.abb.setGeometry(QtCore.QRect(510, 68, 521, 41))
        font = QtGui.QFont()
        font.setFamily("Swis721 BT")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.abb.setFont(font)
        self.abb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.abb.setStyleSheet("border-radius: 10px; color: white;\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.abb.setObjectName("abb")
        self.SUTEXT_12 = QtWidgets.QTextEdit(self.frame)
        self.SUTEXT_12.setEnabled(False)
        self.SUTEXT_12.setGeometry(QtCore.QRect(227, 194, 621, 101))
        font = QtGui.QFont()
        font.setFamily("Centaur")
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.SUTEXT_12.setFont(font)
        self.SUTEXT_12.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.SUTEXT_12.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.SUTEXT_12.setStyleSheet("background-color: transparent; border: none;\n"
"")
        self.SUTEXT_12.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SUTEXT_12.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.SUTEXT_12.setObjectName("SUTEXT_12")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(453, 188, 408, 3))
        self.line_2.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(226, 264, 405, 3))
        self.line_3.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.widget.raise_()
        self.widget_3.raise_()
        self.widget_2.raise_()
        self.SUTEXT_13.raise_()
        self.widget_12.raise_()
        self.abb.raise_()
        self.SUTEXT_12.raise_()
        self.SUTEXT_11.raise_()
        self.line_2.raise_()
        self.line_3.raise_()

        self.retranslateUi(startup)
        QtCore.QMetaObject.connectSlotsByName(startup)

    def retranslateUi(self, startup):
        _translate = QtCore.QCoreApplication.translate
        startup.setWindowTitle(_translate("startup", "MainWindow"))
        self.lib.setText(_translate("startup", "Continue"))
        self.label_25.setText(_translate("startup", "LOG IN!"))
        self.SUTEXT_11.setHtml(_translate("startup", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; color:#cb9230;\">Log in to your NotionBoard account and unlock your world and log in to explore endless possibilities! </span></p></body></html>"))
        self.sub.setText(_translate("startup", "Continue"))
        self.label_28.setText(_translate("startup", " SIGN UP!"))
        self.SUTEXT_13.setHtml(_translate("startup", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; color:#d8823b;\">Join the journey! </span><span style=\" font-family:\'inter-var,-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Apple Color Emoji,Arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol\'; font-size:16pt; color:#d8823b; background-color:#ffffff;\">Turn ideas into action</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'inter-var,-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Apple Color Emoji,Arial,sans-serif,Segoe UI Emoji,Segoe UI Symbol\'; font-size:16pt; color:#d8823b; background-color:#ffffff;\">with NortionBoard,</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:16pt; color:#d8823b;\"> Create your account to start your adventure today. </span></p></body></html>"))
        self.mainpagetext_42.setText(_translate("startup", "NOTIONBOARD"))
        self.mainpagetext_43.setText(_translate("startup", "NOTIONBOARD"))
        self.abb.setText(_translate("startup", "Learn about us!"))
        self.SUTEXT_12.setHtml(_translate("startup", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Centaur\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:18px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:28pt; font-weight:600; color:#000000;\">&quot;Write, plan, organize, notify&quot;</span></p></body></html>"))
