# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\maeve\Desktop\nb_app\ui\todolist_student.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_todolist_student(object):
    def setupUi(self, todolist_student):
        todolist_student.setObjectName("todolist_student")
        todolist_student.resize(792, 726)
        self.main_frm = QtWidgets.QFrame(todolist_student)
        self.main_frm.setGeometry(QtCore.QRect(-40, -20, 1111, 761))
        font = QtGui.QFont()
        font.setFamily("Swis721 BlkOul BT")
        font.setPointSize(27)
        self.main_frm.setFont(font)
        self.main_frm.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.main_frm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frm.setObjectName("main_frm")
        self.frm_nav = QtWidgets.QListWidget(self.main_frm)
        self.frm_nav.setGeometry(QtCore.QRect(60, 40, 201, 471))
        self.frm_nav.setStyleSheet(" border-radius: 20px; border: 1px solid grey; \n"
"background-color: rgb(255, 255, 255);")
        self.frm_nav.setObjectName("frm_nav")
        self.frm_todo = QtWidgets.QListWidget(self.main_frm)
        self.frm_todo.setGeometry(QtCore.QRect(281, 42, 531, 681))
        self.frm_todo.setStyleSheet(" border-radius: 20px; border: 1px solid grey; \n"
"background-color: rgb(255, 255, 255);")
        self.frm_todo.setObjectName("frm_todo")
        self.studtodo_table = QtWidgets.QTreeWidget(self.main_frm)
        self.studtodo_table.setGeometry(QtCore.QRect(311, 126, 471, 491))
        self.studtodo_table.setStyleSheet(" border-radius: 20px; border: 1px solid transparent; \n"
"background-color: rgb(241, 241, 241);")
        self.studtodo_table.setObjectName("studtodo_table")
        self.studtodo_table.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Dubai")
        self.studtodo_table.headerItem().setFont(0, font)
        self.studtodo_table.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Dubai")
        self.studtodo_table.headerItem().setFont(1, font)
        self.studtodo_table.headerItem().setTextAlignment(2, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Dubai")
        self.studtodo_table.headerItem().setFont(2, font)
        self.stud_addtodo_btn = QtWidgets.QPushButton(self.main_frm)
        self.stud_addtodo_btn.setGeometry(QtCore.QRect(309, 640, 481, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display")
        font.setPointSize(15)
        self.stud_addtodo_btn.setFont(font)
        self.stud_addtodo_btn.setStyleSheet("QPushButton {background-color: rgb(21, 21, 21); border-radius: 30px; color: white;}\n"
"\n"
"QPushButton:hover {border-radius: 30px; color: white; background-color: rgb(85, 170, 255);}\n"
"")
        self.stud_addtodo_btn.setText("")
        self.stud_addtodo_btn.setObjectName("stud_addtodo_btn")
        self.removepost_btn = QtWidgets.QPushButton(self.main_frm)
        self.removepost_btn.setGeometry(QtCore.QRect(320, 650, 92, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.removepost_btn.setFont(font)
        self.removepost_btn.setStyleSheet("QPushButton {border-radius: 20px; color: black; background-color: white; }\n"
"\n"
"QPushButton:hover {border-radius: 20px; color: white; background-color: rgb(255, 85, 127);}\n"
"\n"
"")
        self.removepost_btn.setObjectName("removepost_btn")
        self.lb_addtodobtn = QtWidgets.QLabel(self.main_frm)
        self.lb_addtodobtn.setGeometry(QtCore.QRect(526, 659, 83, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Semib")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.lb_addtodobtn.setFont(font)
        self.lb_addtodobtn.setStyleSheet("background-color: none; border: none; \n"
"color: rgb(255, 255, 255);")
        self.lb_addtodobtn.setObjectName("lb_addtodobtn")
        self.tags_todolist = QtWidgets.QPushButton(self.main_frm)
        self.tags_todolist.setEnabled(False)
        self.tags_todolist.setGeometry(QtCore.QRect(310, 70, 130, 37))
        font = QtGui.QFont()
        font.setFamily("Swis721 BT")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tags_todolist.setFont(font)
        self.tags_todolist.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tags_todolist.setStyleSheet("background-color: none; border-radius: 18px; color: black;   border: 1px solid grey;")
        self.tags_todolist.setObjectName("tags_todolist")
        self.notifyme__btn = QtWidgets.QPushButton(self.main_frm)
        self.notifyme__btn.setGeometry(QtCore.QRect(451, 69, 111, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.notifyme__btn.setFont(font)
        self.notifyme__btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.notifyme__btn.setStyleSheet("QPushButton {border-radius: 20px; color: white; background-color: rgb(85, 170, 255);}\n"
"\n"
"QPushButton:hover {border-radius: 20px; border: 1px solid #55AAFF; color: rgb(85, 170, 255); background-color: white; }")
        self.notifyme__btn.setObjectName("notifyme__btn")
        self.lb_greetings = QtWidgets.QLabel(self.main_frm)
        self.lb_greetings.setEnabled(True)
        self.lb_greetings.setGeometry(QtCore.QRect(96, 70, 124, 31))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.lb_greetings.setFont(font)
        self.lb_greetings.setToolTip("")
        self.lb_greetings.setAutoFillBackground(False)
        self.lb_greetings.setStyleSheet("background-color: NONE;")
        self.lb_greetings.setObjectName("lb_greetings")
        self.home_frame = QtWidgets.QFrame(self.main_frm)
        self.home_frame.setGeometry(QtCore.QRect(85, 122, 151, 161))
        self.home_frame.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_frame.setStyleSheet(" border-radius: 20px; \n"
"background-color: rgb(221, 205, 249);")
        self.home_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.home_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.home_frame.setObjectName("home_frame")
        self.label_14 = QtWidgets.QLabel(self.home_frame)
        self.label_14.setGeometry(QtCore.QRect(-50, -150, 200, 198))
        self.label_14.setStyleSheet("background-color: none;\n"
"border-radius: 99%; /* Make it circular */\n"
"border: 2px solid purple ; /* Add a border */\n"
"\n"
"")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.home_frame)
        self.label_15.setGeometry(QtCore.QRect(70, -130, 200, 198))
        self.label_15.setStyleSheet("background-color: none;\n"
"border-radius: 99%; /* Make it circular */\n"
"border: 2px solid purple ; /* Add a border */\n"
"\n"
"")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.mainpagetext_53 = QtWidgets.QLabel(self.home_frame)
        self.mainpagetext_53.setGeometry(QtCore.QRect(23, 62, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Swis721 Blk BT")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.mainpagetext_53.setFont(font)
        self.mainpagetext_53.setToolTip("")
        self.mainpagetext_53.setAutoFillBackground(False)
        self.mainpagetext_53.setStyleSheet("background-color: transparent; border: none;\n"
"color: purple;\n"
"\n"
"\n"
"")
        self.mainpagetext_53.setObjectName("mainpagetext_53")
        self.label_17 = QtWidgets.QLabel(self.home_frame)
        self.label_17.setGeometry(QtCore.QRect(-56, 120, 200, 198))
        self.label_17.setStyleSheet("background-color: none;\n"
"border-radius: 99%; /* Make it circular */\n"
"border: 2px solid purple ; /* Add a border */\n"
"\n"
"")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_16 = QtWidgets.QLabel(self.home_frame)
        self.label_16.setGeometry(QtCore.QRect(-150, -110, 200, 198))
        self.label_16.setStyleSheet("background-color: none;\n"
"border-radius: 99%; /* Make it circular */\n"
"border: 2px solid purple ; /* Add a border */\n"
"\n"
"")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.home_btn = QtWidgets.QPushButton(self.home_frame)
        self.home_btn.setGeometry(QtCore.QRect(0, 0, 151, 161))
        self.home_btn.setStyleSheet(" border-radius: 20px; \n"
"background-color: transparent;")
        self.home_btn.setText("")
        self.home_btn.setObjectName("home_btn")
        self.todo_btn = QtWidgets.QFrame(self.main_frm)
        self.todo_btn.setGeometry(QtCore.QRect(85, 319, 151, 161))
        self.todo_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.todo_btn.setStyleSheet(" border-radius: 20px; \n"
"background-color: rgb(198, 239, 216);")
        self.todo_btn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.todo_btn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.todo_btn.setObjectName("todo_btn")
        self.label_8 = QtWidgets.QLabel(self.todo_btn)
        self.label_8.setGeometry(QtCore.QRect(-88, 120, 200, 198))
        self.label_8.setStyleSheet("background-color: none;\n"
"border-radius: 99%; /* Make it circular */\n"
"border: 2px solid green ; /* Add a border */\n"
"")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.todo_btn)
        self.label_9.setGeometry(QtCore.QRect(-168, -117, 200, 198))
        self.label_9.setStyleSheet("background-color: none;\n"
"border-radius: 99%; /* Make it circular */\n"
"border: 2px solid green ; /* Add a border */\n"
"\n"
"")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.mainpagetext_52 = QtWidgets.QLabel(self.todo_btn)
        self.mainpagetext_52.setGeometry(QtCore.QRect(14, 57, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Swis721 Blk BT")
        font.setPointSize(26)
        self.mainpagetext_52.setFont(font)
        self.mainpagetext_52.setToolTip("")
        self.mainpagetext_52.setAutoFillBackground(False)
        self.mainpagetext_52.setStyleSheet("background-color: transparent; border: none;\n"
"color: green;\n"
"\n"
"\n"
"")
        self.mainpagetext_52.setObjectName("mainpagetext_52")
        self.label_10 = QtWidgets.QLabel(self.todo_btn)
        self.label_10.setGeometry(QtCore.QRect(0, -160, 200, 198))
        self.label_10.setStyleSheet("background-color: none;\n"
"border-radius: 99%; /* Make it circular */\n"
"border: 2px solid green ; /* Add a border */\n"
"\n"
"")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.opt_frame = QtWidgets.QFrame(self.main_frm)
        self.opt_frame.setGeometry(QtCore.QRect(84, 537, 151, 161))
        self.opt_frame.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.opt_frame.setStyleSheet(" border-radius: 20px; \n"
"background-color: rgb(211, 217, 250);")
        self.opt_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.opt_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.opt_frame.setObjectName("opt_frame")
        self.label_12 = QtWidgets.QLabel(self.opt_frame)
        self.label_12.setGeometry(QtCore.QRect(-168, -117, 200, 198))
        self.label_12.setStyleSheet("background-color: none;\n"
"border-radius: 99%; /* Make it circular */\n"
"border: 2px solid blue;\n"
"")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.mainpagetext_61 = QtWidgets.QLabel(self.opt_frame)
        self.mainpagetext_61.setGeometry(QtCore.QRect(38, 56, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Swis721 Blk BT")
        font.setPointSize(24)
        self.mainpagetext_61.setFont(font)
        self.mainpagetext_61.setToolTip("")
        self.mainpagetext_61.setAutoFillBackground(False)
        self.mainpagetext_61.setStyleSheet("background-color: transparent; border: none; \n"
"color: blue;")
        self.mainpagetext_61.setObjectName("mainpagetext_61")
        self.label_11 = QtWidgets.QLabel(self.opt_frame)
        self.label_11.setGeometry(QtCore.QRect(-30, 110, 200, 198))
        self.label_11.setStyleSheet("background-color: none;\n"
"border-radius: 99%; /* Make it circular */\n"
"border: 2px solid blue;\n"
"")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.opt_frame)
        self.label_13.setGeometry(QtCore.QRect(48, -137, 200, 198))
        self.label_13.setStyleSheet("background-color: none;\n"
"border-radius: 99%; /* Make it circular */\n"
"border: 2px solid blue;\n"
"")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.opt_btn = QtWidgets.QPushButton(self.opt_frame)
        self.opt_btn.setGeometry(QtCore.QRect(0, 0, 146, 161))
        self.opt_btn.setStyleSheet(" border-radius: 20px; \n"
"background-color: transparent;")
        self.opt_btn.setText("")
        self.opt_btn.setObjectName("opt_btn")
        self.edittodo_btn = QtWidgets.QPushButton(self.main_frm)
        self.edittodo_btn.setGeometry(QtCore.QRect(570, 69, 71, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.edittodo_btn.setFont(font)
        self.edittodo_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.edittodo_btn.setStyleSheet("QPushButton {border-radius: 20px; color: white; background-color: rgb(255, 85, 127);}\n"
"\n"
"QPushButton:hover {border-radius: 20px; border: 1px solid #FF557F; color: rgb(255, 85, 127); background-color: white; }\n"
"")
        self.edittodo_btn.setObjectName("edittodo_btn")

        self.retranslateUi(todolist_student)
        QtCore.QMetaObject.connectSlotsByName(todolist_student)

    def retranslateUi(self, todolist_student):
        _translate = QtCore.QCoreApplication.translate
        todolist_student.setWindowTitle(_translate("todolist_student", "Dialog"))
        self.studtodo_table.headerItem().setText(0, _translate("todolist_student", "Tags:"))
        self.studtodo_table.headerItem().setText(1, _translate("todolist_student", "Task:"))
        self.studtodo_table.headerItem().setText(2, _translate("todolist_student", "Progress:"))
        self.removepost_btn.setText(_translate("todolist_student", "Remove"))
        self.lb_addtodobtn.setText(_translate("todolist_student", "Add To-Do"))
        self.tags_todolist.setText(_translate("todolist_student", "To-Do List"))
        self.notifyme__btn.setText(_translate("todolist_student", "Notify Me"))
        self.lb_greetings.setText(_translate("todolist_student", "What to-do?"))
        self.mainpagetext_53.setText(_translate("todolist_student", "HOME"))
        self.mainpagetext_52.setText(_translate("todolist_student", "TO-DO"))
        self.mainpagetext_61.setText(_translate("todolist_student", "OPT"))
        self.edittodo_btn.setText(_translate("todolist_student", "Edit"))
